name: Ansible files & Deployment 

on:
  push:
    paths:
      - 'ansible/playbooks/**'
  pull_request:
    paths:
      - 'ansible/playbooks/**'

jobs:
  ansible-lint:
    uses: ansible/ansible-content-actions/.github/workflows/ansible_lint.yaml@main
    with:
      args: '-p ansible/playbooks'
